### ISSUE TITLE
Changing default behavior to no providers instead of all-providers

### ISSUE THREAD

**Issue by LiorLieberman** [kubernetes-sigs/ingress2gateway#158]
**What would you like to be added**:
Default behavior needs to change to not include any provider by default

**Why this is needed**:
Including all provider by default causes us many problems. Two example are https://github.com/kubernetes-sigs/ingress2gateway/issues/127 and https://github.com/kubernetes-sigs/ingress2gateway/issues/138. 

Also, most people would only have have one provider, and in case of more providers installed, they can run the tool multiple times.

/help
/triage accepted

**Comment by LiorLieberman** [comment]
cc: @levikobi @mlavacca

**Comment by mlavacca** [comment]
An additional problem of running all providers by default is that with the addition of the `openapi` provider, now if no provider is passed as argument, the tool tries to use all the regular providers plus `openapi`, which does not really make much sense. I think we should set the providers flag to be mandatory instead of defaulting to all providers.
